In [0]:
import pyspark

In [0]:
df = sqlContext.sql('SELECT * FROM ContainsNull')

In [0]:
df.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp1| John| null|
|emp2| null| null|
|emp3| null|345.0|
|emp4|Cindy|456.0|
+----+-----+-----+

In [0]:
droping_nas = df.na.drop(thresh=2)
droping_nas.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp1| John| null|
|emp3| null|345.0|
|emp4|Cindy|456.0|
+----+-----+-----+

In [0]:
droping_any = df.na.drop(how='any')
droping_any.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp4|Cindy|456.0|
+----+-----+-----+

In [0]:
# drops rows with whole lines in null values
droping_how = df.na.drop(how='all')
droping_how.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp1| John| null|
|emp2| null| null|
|emp3| null|345.0|
|emp4|Cindy|456.0|
+----+-----+-----+

In [0]:
# if any nulls in Sales' column then it drops
droping_sub = df.na.drop(subset = ['Sales'])
droping_sub.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp3| null|345.0|
|emp4|Cindy|456.0|
+----+-----+-----+

In [0]:
# luckily this command fils only these values which are integers, its not being applied on strings
data_fill = df.na.fill(0)
data_fill.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp1| John|  0.0|
|emp2| null|  0.0|
|emp3| null|345.0|
|emp4|Cindy|456.0|
+----+-----+-----+

In [0]:
# filling data only for one column
fill_column = df.na.fill('No name', subset=['Name'])
fill_column.show()

+----+-------+-----+
|  Id|   Name|Sales|
+----+-------+-----+
|emp1|   John| null|
|emp2|No name| null|
|emp3|No name|345.0|
|emp4|  Cindy|456.0|
+----+-------+-----+

In [0]:
from pyspark.sql.functions import mean

In [0]:
mean_value = df.select(mean(df['Sales'])).collect()
mean_value

Out[13]: [Row(avg(Sales)=400.5)]

In [0]:
mean_sales = mean_value[0][0]
mean_sales

Out[14]: 400.5

In [0]:
fill_sales = df.na.fill(mean_sales, ['Sales'])
fill_sales.show()

+----+-----+-----+
|  Id| Name|Sales|
+----+-----+-----+
|emp1| John|400.5|
|emp2| null|400.5|
|emp3| null|345.0|
|emp4|Cindy|456.0|
+----+-----+-----+